

/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
package org.apache.rocketmq.filter.parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SelectorParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int LINE_COMMENT = 6;
    /**
     * RegularExpression Id.
     */
    int BLOCK_COMMENT = 7;
    /**
     * RegularExpression Id.
     */
    int NOT = 8;
    /**
     * RegularExpression Id.
     */
    int AND = 9;
    /**
     * RegularExpression Id.
     */
    int OR = 10;
    /**
     * RegularExpression Id.
     */
    int BETWEEN = 11;
    /**
     * RegularExpression Id.
     */
    int IN = 12;
    /**
     * RegularExpression Id.
     */
    int TRUE = 13;
    /**
     * RegularExpression Id.
     */
    int FALSE = 14;
    /**
     * RegularExpression Id.
     */
    int NULL = 15;
    /**
     * RegularExpression Id.
     */
    int IS = 16;
    /**
     * RegularExpression Id.
     */
    int DECIMAL_LITERAL = 17;
    /**
     * RegularExpression Id.
     */
    int FLOATING_POINT_LITERAL = 18;
    /**
     * RegularExpression Id.
     */
    int EXPONENT = 19;
    /**
     * RegularExpression Id.
     */
    int STRING_LITERAL = 20;
    /**
     * RegularExpression Id.
     */
    int ID = 21;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] TOKEN_IMAGE = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "<LINE_COMMENT>",
            "<BLOCK_COMMENT>",
            "\"NOT\"",
            "\"AND\"",
            "\"OR\"",
            "\"BETWEEN\"",
            "\"IN\"",
            "\"TRUE\"",
            "\"FALSE\"",
            "\"NULL\"",
            "\"IS\"",
            "<DECIMAL_LITERAL>",
            "<FLOATING_POINT_LITERAL>",
            "<EXPONENT>",
            "<STRING_LITERAL>",
            "<ID>",
            "\"=\"",
            "\"<>\"",
            "\">\"",
            "\">=\"",
            "\"<\"",
            "\"<=\"",
            "\"(\"",
            "\",\"",
            "\")\"",
            "\"+\"",
            "\"-\"",
    };

}
